version: '3.8'

services:
  autodocker:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - /tmp:/tmp  # 用於 zbpack 臨時文件
    networks:
      - autodocker-network

networks:
  autodocker-network:
    driver: bridge
